# Generated by Django 5.0.7 on 2024-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccesstoken',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiry'),
        ),
    ]
