# Generated by Django 5.0.6 on 2024-06-22 13:08

import django.core.validators
import django.db.models.deletion
import houses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('order', models.IntegerField(verbose_name='order')),
            ],
            options={
                'verbose_name': 'energy certificate',
                'verbose_name_plural': 'energy certificates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HouseCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('order', models.IntegerField(verbose_name='order')),
            ],
            options={
                'verbose_name': 'house condition',
                'verbose_name_plural': 'house conditions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'house type',
                'verbose_name_plural': 'house types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseTypology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('order', models.IntegerField(verbose_name='order')),
            ],
            options={
                'verbose_name': 'house typology',
                'verbose_name_plural': 'house typologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'locale',
                'verbose_name_plural': 'locales',
                'ordering': ['parish__municipality__district__country__name', 'parish__municipality__district__name', 'parish__municipality__name', 'parish__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['country__name', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{4}-\\d{3}', message='Not a valid postal-code. Pattern must be: XXXX-XXX')], verbose_name='postal code')),
                ('price_in_euros', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price in euros')),
                ('discount_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='discount in euros')),
                ('gross_private_area_in_square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='gross private area in square meters')),
                ('net_internal_area_in_square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='net internal area in square meters')),
                ('construction_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)], verbose_name='construction year')),
                ('number_of_rooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of rooms')),
                ('number_of_bathrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of bathrooms')),
                ('has_garage', models.BooleanField(default=False, verbose_name='has garage')),
                ('highlighted', models.BooleanField(default=False, verbose_name='highlighted')),
                ('reserved', models.BooleanField(default=False, verbose_name='reserved')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('sold_at', models.DateField(blank=True, null=True, verbose_name='sold at')),
                ('sold_for', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='sold for')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='order')),
                ('energy_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='houses.energycertificate', verbose_name='energy certificate')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='houses.housecondition', verbose_name='condition')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.housetype', verbose_name='type')),
                ('typology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='houses.housetypology', verbose_name='typology')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'ordering': ['-highlighted', 'order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HouseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=houses.models.house_file_upload_to, verbose_name='file')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('filename', models.CharField(editable=False, max_length=255, verbose_name='filename')),
                ('content_type', models.CharField(editable=False, max_length=50, verbose_name='content type')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='order')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house', verbose_name='house')),
            ],
            options={
                'verbose_name': 'house file',
                'verbose_name_plural': 'house files',
                'ordering': ['-house', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.district', verbose_name='district')),
            ],
            options={
                'verbose_name': 'municipality',
                'verbose_name_plural': 'municipalities',
                'ordering': ['district__country__name', 'district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.municipality', verbose_name='municipality')),
            ],
            options={
                'verbose_name': 'parish',
                'verbose_name_plural': 'parishes',
                'ordering': ['municipality__district__country__name', 'municipality__district__name', 'municipality__name', 'name'],
                'unique_together': {('municipality', 'name')},
            },
        ),
        migrations.AddField(
            model_name='locale',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.parish', verbose_name='parish'),
        ),
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together={('parish', 'name')},
        ),
    ]
