# Generated by Django 5.0.7 on 2024-07-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housefile',
            options={'ordering': ['order'], 'verbose_name': 'house file', 'verbose_name_plural': 'house files'},
        ),
        migrations.AlterField(
            model_name='housefile',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='houses.house', verbose_name='house'),
        ),
    ]
