# Generated by Django 5.0.7 on 2024-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_housefile_options_alter_housefile_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='adapted_for_reduced_mobility',
            field=models.BooleanField(blank=True, null=True, verbose_name='is adapted for people with reduced mobility'),
        ),
        migrations.AddField(
            model_name='house',
            name='floor_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='floor level'),
        ),
        migrations.AddField(
            model_name='house',
            name='garage_included_in_price',
            field=models.BooleanField(blank=True, null=True, verbose_name='garage included in price'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_balcony',
            field=models.BooleanField(blank=True, null=True, verbose_name='has balcony'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_garden',
            field=models.BooleanField(blank=True, null=True, verbose_name='has garden'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_lift',
            field=models.BooleanField(blank=True, null=True, verbose_name='has lift'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_pool',
            field=models.BooleanField(blank=True, null=True, verbose_name='has pool'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_terrace',
            field=models.BooleanField(blank=True, null=True, verbose_name='has terrace'),
        ),
        migrations.AlterField(
            model_name='house',
            name='has_garage',
            field=models.BooleanField(blank=True, null=True, verbose_name='has garage'),
        ),
    ]
