# Generated by Django 5.0.7 on 2024-07-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_countrytax_pricingtier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrytax',
            options={'ordering': ['country', 'tax_rate'], 'verbose_name': 'country tax', 'verbose_name_plural': 'country taxes'},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'house type', 'verbose_name_plural': 'houses types'},
        ),
        migrations.AddField(
            model_name='housetype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', related_query_name='child', to='houses.housetype', verbose_name='parent type'),
        ),
    ]
